import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next. These are anchored at the
    // project root, so each one needs a `**/` twin for the copies that turn
    // up inside a git worktree under .claude/.
    ".next/**",
    "**/.next/**",
    "out/**",
    "**/out/**",
    "build/**",
    "next-env.d.ts",

    // Agent worktrees: a second checkout of this repo, with its own build
    // output. Linting one reported 4,511 problems against minified webpack
    // chunks and drowned the 23 real ones in the source tree.
    ".claude/worktrees/**",

    // Generated by next-pwa on every build, gitignored, and not ours to fix.
    "public/sw.js",
    "public/sw.js.map",
    "public/workbox-*.js",
    "public/worker-*.js",
    "public/fallback-*.js",
    "public/swe-worker-*.js",
  ]),

  // CommonJS test harnesses. scripts/*.test.cjs run under `node --test` and
  // load modules with require() because that is what .cjs means - the rules
  // banning it are there for application code, which is ESM. Without this the
  // lint is permanently 16 errors red, which is how a real error gets missed.
  {
    files: ["scripts/**/*.cjs"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      "@next/next/no-assign-module-variable": "off",
    },
  },
]);

export default eslintConfig;
