const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs')
const BASE='https://localhost:3443',ACTIVE='Your online offer is active · SOFAEXTRA · FREE UK Mainland Delivery',PROMPT='Your online sofa offer is active'
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),results={}
const P={electric:{variant_id:'1ba97d1f-f890-48f8-8ab9-57cbb147f388',quantity:1,price:999,title:'Hannah Electric Corner',color:'Beige',image_url:''},roma:{variant_id:'4b6dc9c2-91ec-432f-9735-abb6899b1a95',quantity:1,price:350,title:'Roma Recliner 2 Seater Manual Sofa',color:'Black',image_url:''},standard:{variant_id:'ff3c0414-77ba-40ef-b6b2-bd97bff2bd17',quantity:1,price:649,title:'Bishop U shaped Scattered Back Sofa',color:'Truffle',image_url:''}}
const long={variant_id:'a5d2050d-c458-4e0c-b3b3-7b7c727845a0',quantity:1,price:549,title:'Verona 4 Seater Corner 1c2 High Back',color:'Grey',image_url:'',fabric_id:'6ce3d2c2-7f92-4276-b991-70afa07c0cf9',fabric_label:'Chenille Grey',fabric_code:'CH12',fabric_swatch:null}
function pass(k){results[k]='PASS';console.log(k+'=PASS')}
function instrument(p){const s={qualify:0,status:0,genuine:[]};p.on('request',r=>{if(r.url().includes('/api/offer/qualify'))s.qualify++;if(r.url().includes('/api/offer/status'))s.status++});p.on('pageerror',e=>{const x=String(e.stack||e);if(!/Failed to register a ServiceWorker|SSL certificate error/i.test(x))s.genuine.push(x)});p.on('console',m=>{if(m.type()==='error'&&/(?:Uncaught|TypeError|ReferenceError|Unhandled|Hydration|Minified React error)/i.test(m.text()))s.genuine.push(m.text())});return s}
async function persistent(dir,w=390,consent='denied'){const c=await chromium.launchPersistentContext(dir,{headless:true,viewport:{width:w,height:w<=430?900:1000},hasTouch:w<=430,isMobile:w<=430,ignoreHTTPSErrors:true,serviceWorkers:'allow',args:['--ignore-certificate-errors','--allow-insecure-localhost']});await c.addInitScript(x=>localStorage.setItem('cookie_consent',x),consent);return c}
async function fresh(w=390){const b=await chromium.launch({headless:true,args:['--ignore-certificate-errors','--allow-insecure-localhost']});const c=await b.newContext({viewport:{width:w,height:w<=430?900:1000},hasTouch:w<=430,isMobile:w<=430,ignoreHTTPSErrors:true,serviceWorkers:'allow'});await c.addInitScript(()=>localStorage.setItem('cookie_consent','denied'));return{b,c}}
async function status(p){return p.evaluate(async()=>{const r=await fetch('/api/offer/status',{cache:'no-store'});return r.json()})}
async function goto(p,path){const r=await p.goto(BASE+path,{waitUntil:'domcontentloaded',timeout:30000});assert(r&&r.status()<500);await p.locator('body').waitFor({state:'visible'})}
async function waitActive(p){await p.getByText(ACTIVE,{exact:true}).waitFor({state:'visible',timeout:15000});assert((await status(p)).active)}
async function closePrompt(p){const d=p.getByRole('dialog',{name:PROMPT});if(await d.isVisible().catch(()=>false))await d.getByRole('button',{name:/Close your online sofa offer is active/i}).click()}
async function cart(p,items){await p.evaluate(x=>localStorage.setItem('uksofashop_cart',JSON.stringify(x)),items);await goto(p,'/checkout');await p.getByRole('button',{name:/Continue to delivery/i}).waitFor({state:'visible',timeout:12000})}
async function delivery(p){await p.getByRole('button',{name:/Continue to delivery/i}).click();await p.getByText('Delivery Information',{exact:true}).waitFor({timeout:12000})}
async function summary(p,w){if(w>=1024){const a=p.locator('[data-ground="dark"]').filter({hasText:'Order Summary'});for(let i=(await a.count())-1;i>=0;i--)if(await a.nth(i).isVisible().catch(()=>false))return a.nth(i).innerText()}const t=p.locator('[data-bottom-bar] button[aria-controls="mobile-summary"]');await t.waitFor({state:'visible'});if((await t.getAttribute('aria-expanded'))!=='true')await t.click();return p.locator('#mobile-summary [data-ground="dark"]').innerText()}
async function fillPersist(w){const{b,c}=await fresh(w),p=await c.newPage(),st=instrument(p);await goto(p,'/?gclid=QA_P2DA_'+w);await waitActive(p);await closePrompt(p);await cart(p,[P.standard]);await delivery(p);await p.waitForFunction(()=>document.body.innerText.includes('Online offer applied · £20 off'));const vals={customerName:'QA Phase C',customerEmail:'qa.phasec@example.invalid',customerPhone:'07123456789',postcode:'BB1 1AA',shippingAddress:'1 QA Street, Blackburn',specialInstructions:'Phase C persistence'};for(const n of ['customerName','customerEmail','customerPhone'])await p.locator(`input[name="${n}"]`).fill(vals[n]);const pc=p.locator('label').filter({hasText:/Postcode/}).locator('xpath=following-sibling::div//input');await pc.fill(vals.postcode);await p.locator('textarea[name="shippingAddress"]').fill(vals.shippingAddress);await p.locator('textarea[name="specialInstructions"]').fill(vals.specialInstructions);await p.getByRole('button',{name:/Back to Cart/i}).click();await delivery(p);for(const n of ['customerName','customerEmail','customerPhone'])assert.strictEqual(await p.locator(`input[name="${n}"]`).inputValue(),vals[n]);assert.strictEqual(await pc.inputValue(),vals.postcode);assert.strictEqual(await p.locator('textarea[name="shippingAddress"]').inputValue(),vals.shippingAddress);assert.strictEqual(await p.locator('textarea[name="specialInstructions"]').inputValue(),vals.specialInstructions);assert((await summary(p,w)).includes('−£20.00'));assert.deepStrictEqual(st.genuine,[]);await c.close();await b.close();pass('P2DA_'+w)}

;(async()=>{
 let c=await persistent('/tmp/profile-a',390),p=c.pages()[0]||await c.newPage(),st=instrument(p);await goto(p,'/?utm_source=google&utm_medium=cpc');await waitActive(p);await closePrompt(p);assert.strictEqual(st.qualify,1);const before=(await status(p)).expiresAt;await goto(p,'/');await waitActive(p);assert.strictEqual(st.qualify,1);assert.strictEqual((await status(p)).expiresAt,before);await goto(p,'/?utm_source=google&utm_medium=organic');await waitActive(p);assert.strictEqual(st.qualify,1);assert.deepStrictEqual(st.genuine,[]);await c.close();c=await persistent('/tmp/profile-a',390);p=c.pages()[0]||await c.newPage();st=instrument(p);await goto(p,'/');await waitActive(p);assert.strictEqual(st.qualify,0);assert.deepStrictEqual(st.genuine,[]);await c.close();pass('PROFILE_A_GOOGLE_PERSISTENT');pass('SAME_PROFILE_REOPEN')
 c=await persistent('/tmp/profile-b',390);p=c.pages()[0]||await c.newPage();st=instrument(p);await goto(p,'/?utm_source=meta&utm_medium=paid_social');await waitActive(p);assert.strictEqual((await status(p)).source,'meta_ads');assert.strictEqual(st.qualify,1);await c.close();pass('PROFILE_B_META')
 for(const [dir,key] of [['/tmp/profile-c','PROFILE_C_ORGANIC'],['/tmp/profile-d','PROFILE_D_CLEAN']]){c=await persistent(dir,390);p=c.pages()[0]||await c.newPage();st=instrument(p);await goto(p,'/');await sleep(900);assert(!(await status(p)).active);assert.strictEqual(st.qualify,0);assert(!(await p.locator('body').innerText()).includes(ACTIVE));await c.close();pass(key)}
 c=await persistent('/tmp/profile-e',390);p=c.pages()[0]||await c.newPage();st=instrument(p);await goto(p,'/?gclid=QA_EXPIRY_1');await waitActive(p);await closePrompt(p);const first=(await status(p)).startedAt;let offer=(await c.cookies()).find(x=>x.name==='uksofashop_offer');assert(offer&&offer.httpOnly&&offer.secure&&offer.sameSite==='Lax');const ctl=await fetch('https://localhost:5443/__qa/expire-all',{method:'POST'});assert(ctl.ok);await goto(p,'/');await sleep(900);assert(!(await status(p)).active);assert(!(await p.locator('body').innerText()).includes(ACTIVE));offer=(await c.cookies()).find(x=>x.name==='uksofashop_offer');assert(!offer,'expired cookie not cleared');await cart(p,[P.electric]);await delivery(p);await sleep(700);let txt=await summary(p,390);assert(!txt.includes('Online offer')&&!txt.includes('−£50.00'));const trig=p.getByRole('button',{name:/Have an offer code\?/i});if(await trig.isVisible().catch(()=>false))await trig.click();await p.getByLabel('Offer code').fill('SOFAEXTRA');await p.getByRole('button',{name:/^Apply$/i}).click();await p.waitForFunction(()=>document.body.innerText.includes('Offer · SOFAEXTRA'));txt=await summary(p,390);assert(txt.includes('−£50.00'));await goto(p,'/?gclid=QA_EXPIRY_2');await waitActive(p);const second=(await status(p)).startedAt;assert(second&&second!==first);await p.getByRole('dialog',{name:PROMPT}).waitFor({state:'visible',timeout:12000});assert.deepStrictEqual(st.genuine,[]);await c.close();pass('PROFILE_E_EXPIRY');pass('NEW_PAID_AFTER_EXPIRY')
 await fillPersist(430);await fillPersist(1440)
 {const{b,c}=await fresh(390),p=await c.newPage(),st=instrument(p);await goto(p,'/?gclid=QA_P2DB_MULTI');await waitActive(p);await closePrompt(p);await cart(p,[long,P.roma,P.standard]);let body=await p.locator('body').innerText();for(const x of [long.title,'Chenille Grey · CH12','£549',P.roma.title,'£350',P.standard.title,'£649'])assert(body.includes(x),x);for(const item of [long,P.roma,P.standard]){const r=await p.getByRole('button',{name:`Remove ${item.title} from your cart`}).boundingBox();assert(r&&r.width>=43&&r.height>=43)}await p.getByRole('button',{name:`Remove ${P.roma.title} from your cart`}).click();await p.getByRole('button',{name:/Undo/i}).waitFor({state:'visible',timeout:3000});await p.getByRole('button',{name:/Undo/i}).click();await p.getByText(P.roma.title,{exact:true}).waitFor();await delivery(p);await p.waitForFunction(()=>document.body.innerText.includes('Online offer applied · £30 off'));const text=await summary(p,390);assert(text.includes('£1548.00')&&text.includes('−£30.00')&&text.includes('£1518.00'));assert(!text.includes('−£20.00')&&!text.includes('−£50.00'));assert.deepStrictEqual(st.genuine,[]);await c.close();await b.close();pass('P2DB_MULTI_ORDER_LEVEL')}
 fs.writeFileSync('/tmp/phasec-supplement-results.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2))
})().catch(e=>{console.error(e.stack||e);process.exit(1)})
